name: Develop

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
        name:
          description: "Develop-Build"
          default: "Generate develop build"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out branch
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Build SampleApplication
        run: ./gradlew --no-daemon build

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test --stacktrace

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

        
